@baseUrl = http://localhost:3000
# @baseUrl = https://api.soalhub.my.id

### Create a new user
POST {{baseUrl}}/users
Content-Type: application/json

{
  "name": "John Doe",
  "email": "john.doe@example.com",
  "password": "password123"
}

### Update a user by ID
PUT {{baseUrl}}/users/2
Content-Type: application/json

{
  "email": "john.doe@example.com",
  "code": "999411"
}

### Get all users
GET {{baseUrl}}/users

### Delete a user by ID
DELETE {{baseUrl}}/users/1