# @baseUrl = http://localhost:3000
@baseUrl = https://api.soalhub.my.id

### Create a new user
POST {{baseUrl}}/users
Content-Type: application/json

{
  "name": "John Doe",
  "email": "john.doe@example.com"
}